name: CI-CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # force Node.js 24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6   # latest checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4  # latest setup-node
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test